server:
  port: 8092
  servlet:
    context-path: /property-view
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  application:
    name: hotel-app

  datasource:
    url: jdbc:h2:mem:hotel-app_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    liquibase: INFO